repos:
  - repo: https://github.com/lbarcziova/changelog-check
    rev: 28996d2116bf21a82d5072eea98776be4986531b
    hooks:
      - id: changelog-check
        stages: [manual, push]
        args: [https://github.com/lbarcziova/testing]
