name: Move PRs into the Kanban board

on:
  pull_request_target:

jobs:
  add-labaled-pr-to-the-kanban-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/lbarcziova/projects/1/views/1
          github-token: ${{ secrets.BOARD_TOKEN }}
